"""add receipt_item_categories

Revision ID: 8b8d02047b88
Revises: fd080f64c708
Create Date: 2026-05-14 10:55:28.488392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8d02047b88'
down_revision: Union[str, Sequence[str], None] = 'fd080f64c708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('use_fallback', sa.Boolean(), nullable=True),
    sa.Column('use_llm', sa.Boolean(), nullable=True),
    sa.Column('use_cache', sa.Boolean(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['receipt_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_item_categories_id'), 'receipt_item_categories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_item_categories_id'), table_name='receipt_item_categories')
    op.drop_table('receipt_item_categories')
    # ### end Alembic commands ###
